service:
  name: kaskadi-stock-report-lambda

package:
  individually: true
  exclude:
    - "**/**"

provider:
  name: aws
  runtime: nodejs10.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  deploymentBucket:
    name: ${env:SLS_DEPLOY_BUCKET}
  deploymentPrefix: ${self:service.name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: !Ref KaskadiWeeklyStockReport

functions:
  KaskadiStockReport:
    handler: kaskadi-stock-report-lambda.handler
    name: ${self:service.name}
    package:
      include:
        - 'kaskadi-stock-report-lambda.js'
        - 'node_modules/**'
    environment:
      TOPIC_ARN: !Ref KaskadiWeeklyStockReport
    events:
      - schedule: rate(5 minutes)

resources:
  Resources:
    KaskadiWeeklyStockReport:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: KaskadiWeeklyStockReport
        DisplayName: Weekly stock update
        Subscription:
          - Endpoint: "a.lemaire@klimapartner.de"
            Protocol: email
