service:
  name: kaskadi-stock-report-lambda

package:
  individually: true
  exclude:
    - "**/**"

provider:
  name: aws
  runtime: nodejs10.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  deploymentBucket:
    name: ${env:SLS_DEPLOY_BUCKET}
  deploymentPrefix: ${self:service.name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: !Ref KaskadiStockReporter
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: !Ref TestKaskadiStockReporter

functions:
  KaskadiStockReport:
    handler: kaskadi-stock-report-lambda.handler
    name: ${self:service.name}
    layers:
      - !ImportValue KaskadiEsLayerArn
    package:
      include:
        - 'kaskadi-stock-report-lambda.js'
        - 'helpers/**'
        - 'node_modules/**'
    environment:
      TOPIC_ARN: !Ref KaskadiStockReporter
      TEST_TOPIC_ARN: !Ref TestKaskadiStockReporter
      ES_ID: ${env:ES_ID}
      ES_SECRET: ${env:ES_SECRET}
      ES_ENDPOINT: ${env:ES_ENDPOINT}
    events:
      - schedule:
          rate: cron(0 7 * * ? 1) # runs every monday at 7AM
          enabled: true

resources:
  Resources:
    KaskadiStockReporter:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: KaskadiStockReporter
        DisplayName: Klimapartner's stock autoreporter
        Subscription:
          - Endpoint: "a.lemaire@klimapartner.de"
            Protocol: email
          - Endpoint: "j.will@klimapartner.de"
            Protocol: email
    # test topic
    TestKaskadiStockReporter:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: TestKaskadiStockReporter
        DisplayName: Test Klimapartner's stock autoreporter
        Subscription:
          - Endpoint: "a.lemaire@klimapartner.de"
            Protocol: email
