service:
  name: kaskadi-stock-report-lambda

package:
  individually: true
  exclude:
    - '.*/**'
    - '*'

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: kaskadi-serverless-deployment-bucket
  tags:
    app: kaskadi
    service: ${self:service.name}
    logical-unit: stocks
    type: schedule

functions:
  KaskadiStockReport:
    handler: kaskadi-stock-report-lambda.handler
    name: ${self:service.name}
    layers:
      - !Ref LayerLambdaLayer
    package:
      include:
        - 'kaskadi-stock-report-lambda.js'
    environment:
      ES_ID: ${env:ES_ID}
      ES_SECRET: ${env:ES_SECRET}
      ES_ENDPOINT: ${env:ES_ENDPOINT}
      NODE_PATH: /opt/nodejs/utils:/opt/nodejs/node12/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules:/var/runtime:/var/task
    events:
      - schedule:
          rate: cron(0 7 ? * MON *) # runs every monday at 7AM
          enabled: true

layers:
  Layer:
    path: layer
    name: ${self:service.name}-layer
    description: Layer for ${self:service.name}
    compatibleRuntimes:
      - nodejs10.x
      - nodejs12.x
    licenseInfo: MIT
